######################## Functions #####################
[]
prelude =
    langpro_path = "../LangProLRC/"

    def part_to_sick_filename(part):
        d = {'trial': 'SICK_trial',
             'train': 'SICK_train',
             'test':  'SICK_test_annotated',
             'test_annotated':  'SICK_test_annotated',
             'train_trial': 'SICK_train_trial'
            }
        return d[part]

#########################################################
# utils
#########################################################

[tsv/%{dataset}]
recipe =
    mkdir  -p datasets/%{dataset}/
    for f in `ls tsv/%{dataset}/*.tsv | xargs -n 1 basename`
    do
        python3 scripts/nlidata2prolog.py  tsv/%{dataset}/$f  datasets/%{dataset}/${f/.tsv/_sen.pl} --fmt sen.pl  --tokenize nltk_apo  --corpus %{dataset}
    done
    echo "--sen done--"

    for f in `ls tsv/%{dataset}/*.tsv | xargs -n 1 basename`
    do
        python3 scripts/nlidata2prolog.py  tsv/%{dataset}/$f  datasets/%{dataset}/${f/tsv/spl} --fmt spl  --tokenize nltk_apo --corpus %{dataset}
    done
    echo "--spl done--"

    for f in `ls datasets/%{dataset}/*.spl | xargs -n 1 basename`
    do
        cat datasets/%{dataset}/$f | ../candc/candc/bin/candc --models ../candc/models/models --output datasets/%{dataset}/${f/.spl/_cc_ccg.pl}  --candc-printer boxer --candc-parser-noisy_rules=false 2> datasets/%{dataset}/${f/.spl/_output.txt} 
        # cat datasets/%{dataset}/$f | ../candc/candc/bin/candc --models ../candc/models/models --output datasets/%{dataset}/${f/.spl/_cc_ccg.pl}  --candc-printer boxer --candc-parser-noisy_rules=false
        echo "${f/.spl/_cc_ccg.pl} Done"
        grep -o -i failed datasets/%{dataset}/${f/.spl/_output.txt}  | wc -l
    done
    echo "---ccg done---"

    python scripts/get_failed.py --dataset %{dataset}
    echo "---failed done---"

# run all because 
[lex_pairs/%{dataset}]
recipe =
    python scripts_ccg/ccg_main.py --dataset %{dataset}

########### Clues #########
# specify part of dataset
[lex_preds/%{dataset}/clues/%{part}]
recipe = 
    python scripts_clues/csv2pred_raw.py --dataset %{dataset} --part %{part}

# add dependency
[lex_KB/%{dataset}/clues/%{part}]
recipe = 
    python scripts_clues/to_prolog.py --dataset %{dataset} --part %{part} --model clues

# run all from dataset using 
[lex_preds/%{dataset}/clues]
recipe = 
    python scripts_clues/csv2pred_raw.py --dataset %{dataset} --part all

# add dependency
[lex_KB/%{dataset}/clues]
recipe = 
    python scripts_clues/to_prolog.py --dataset %{dataset} --part all --model clues


########### NLI #########
# specify part of dataset
[lex_preds/%{dataset}/NLI/%{part}/pred]
recipe = 
    python scripts_NLI/2_SICK_NLI_predict.py --dataset %{dataset} --part %{part} --output lex_preds/%{dataset}/NLI/pred/

# run all from dataset using 
[lex_preds/%{dataset}/NLI/pred]
recipe = 
    python scripts_NLI/2_SICK_NLI_predict.py --dataset %{dataset} --part all --output lex_preds/%{dataset}/NLI/pred/

[lex_preds/%{dataset}/NLI/%{part}]
recipe = 
    python scripts_NLI/1_make_templates.py --dataset %{dataset} --part %{part}

# run all from dataset using 
[lex_preds/%{dataset}/NLI]
recipe = 
    python scripts_NLI/1_make_templates.py --dataset %{dataset} --part all

# run all from dataset using 
[lex_KB/%{dataset}/NLI]
recipe = 
    python scripts_NLI/3_predict_using_tree.py --dataset %{dataset} --part all

# add dependency
[lex_KB/%{dataset}/NLI/%{part}]
recipe = 
    python scripts_NLI/3_predict_using_tree.py --dataset %{dataset} --part all --model clues

# LANGPRO
[results/%{dataset}/LRC/%{model}/%{part}.ans]
dep.main = %{langpro_path}/prolog/main.pl
dep.sen = %{langpro_path}/ccg_sen_d/%{ part_to_sick_filename(part) }_sen.pl
dep.parser_pl = %{langpro_path}/ccg_sen_d/%{ part_to_sick_filename(part) }_eccg.pl
dep.wn =  %{langpro_path}/WNProlog/wn.pl
LRC_file = lex_KB/%{dataset}/%{model}/final/%{part}_lemma_idx.pl
log = results/%{dataset}/LRC/%{model}/%{part}.log
recipe =
    mkdir -p results/%{dataset}/LRC/%{model}/
    swipl -g "parList([parallel(_), aall, wn_ant, wn_sim, wn_der, no_kb, ind_kb, constchk, ral(100), allInt, waif('%{target}')]), entail_all" -t halt -f %{main}  %{parser_pl} %{sen} %{wn} %{LRC_file}> %{log} 2>&1


[results/%{dataset}/LRC/%{model}]
recipe =
    echo %{dataset} %{model}
    produce -b results/%{dataset}/LRC/%{model}/trial.ans
    produce -b results/%{dataset}/LRC/%{model}/train.ans
    produce -b results/%{dataset}/LRC/%{model}/train_trial.ans
    produce -b results/%{dataset}/LRC/%{model}/test_annotated.ans
    
    notify-send -u critical "Script Done"