######################## Functions #####################
[]
prelude =
    langpro_path = "../LangProAbd/"

    def part_to_sick_filename(part):
        d = {'trial': 'SICK_trial',
             'train': 'SICK_train',
             'test':  'SICK_test_annotated',
             'test_annotated':  'SICK_test_annotated',
             'train_trial': 'SICK_train_trial'
            }
        if part not in d:
            return part
        else:
            return d[part]

#########################################################
# utils
#########################################################
[new_tree]
recipe = 
    python /home/thomas/UU/thesis/CCG_parse/scripts_NLI/1_make_templates.py --dataset merged_LRC_words --baseline True --part train
    python /home/thomas/UU/thesis/CCG_parse/scripts_NLI/1_make_templates.py --dataset merged_LRC_words --baseline True --part test
    python /home/thomas/UU/thesis/CCG_parse/scripts_NLI/1_make_templates.py --dataset merged_LRC_words --baseline True --part validation

    python /home/thomas/UU/thesis/CCG_parse/scripts_NLI/1_make_templates.py --dataset ppdb_phrase --baseline True --part ppdb_scrape_disjoint
    
    produce -b lex_preds/ppdb_phrase/NLI/pred
    produce -b lex_preds/merged_LRC_words/NLI/pred

    python /home/thomas/UU/thesis/CCG_parse/scripts_NLI/2.5_train_decision_tree.py
    python /home/thomas/UU/thesis/CCG_parse/scripts_NLI/2.7_visualise_decision_tree.py


[datasets/SNLI_5_anno]
recipe = 
    mkdir -p datasets/SNLI_5_anno
    for f in `ls datasets/SNLI_5_anno_org/*.jsonl | xargs -n 1 basename`
    do
        python3 scripts_other/nlidata2prolog.py  datasets/SNLI_5_anno_org/$f  datasets/SNLI_5_anno/${f/.jsonl/_sen.pl} --fmt sen.pl  --tokenize native  --corpus snlijson
    done
    echo "--sen done--"

    for f in `ls datasets/SNLI_5_anno_org/*.jsonl | xargs -n 1 basename`
    do
        python3 scripts_other/nlidata2prolog.py   datasets/SNLI_5_anno_org/$f  datasets/SNLI_5_anno/${f/jsonl/spl} --fmt spl  --tokenize native --corpus snlijson
    done
    echo "--spl done--"

    for f in `ls datasets/SNLI_5_anno/*.spl | xargs -n 1 basename`
    do
        # --candc-int-dict_cutoffs="20 20 20 20 150 200 500" --candc-int-betas="0.075 0.03 0.01 0.005 0.001 0.0005 0.00001"
        cat datasets/SNLI_5_anno/$f | ../candc/candc/bin/candc --models ../candc/models/models --output datasets/SNLI_5_anno/${f/.spl/_ccg.pl}  --candc-printer boxer --candc-parser-noisy_rules=false 2> datasets/SNLI_5_anno/${f/.spl/_output.txt} 
        echo "${f/.spl/_cc_ccg.pl} Done"
        grep -o -i failed datasets/SNLI_5_anno/${f/.spl/_output.txt}  | wc -l
    done
    echo "---ccg done---"

# run all because 
[lex_pairs/%{dataset}]
recipe =
    python scripts_ccg/ccg_main.py --dataset %{dataset}

########### Clues #########
# specify part of dataset
[lex_preds/%{dataset}/clues/%{part}]
recipe = 
    python scripts_clues/csv2pred_raw.py --dataset %{dataset} --part %{part}

# add dependency
[lex_KB/%{dataset}/clues/%{part}]
recipe = 
    python scripts_clues/to_prolog.py --dataset %{dataset} --part %{part} --model clues

# run all from dataset using 
[lex_preds/%{dataset}/clues]
recipe = 
    python scripts_clues/csv2pred_raw.py --dataset %{dataset} --part all

# add dependency
[lex_KB/%{dataset}/clues]
recipe = 
    python scripts_clues/to_prolog.py --dataset %{dataset} --part all --model clues


########### NLI #########
# run all from dataset using 
[lex_preds/merged_LRC_words/NLI/pred]
recipe = 
    python scripts_NLI/2_SICK_NLI_predict.py --dataset merged_LRC_words --part all --output lex_preds/merged_LRC_words/NLI/pred/ --baseline True

[lex_preds/ppdb_phrase/NLI/pred]
recipe = 
    python scripts_NLI/2_SICK_NLI_predict.py --dataset ppdb_phrase --part all --output lex_preds/ppdb_phrase/NLI/pred/ --baseline True

[lex_preds/%{dataset}/NLI/pred/%{part}]
recipe = 
    python scripts_NLI/2_SICK_NLI_predict.py --dataset %{dataset} --part %{part} --output lex_preds/%{dataset}/NLI/pred/

[lex_preds/%{dataset}/NLI/pred]
recipe = 
    python scripts_NLI/2_SICK_NLI_predict.py --dataset %{dataset} --part all --output lex_preds/%{dataset}/NLI/pred/

[lex_preds/%{dataset}/NLI/%{part}]
recipe = 
    python scripts_NLI/1_make_templates.py --dataset %{dataset} --part %{part}

# run all from dataset using 
[lex_preds/%{dataset}/NLI]
recipe = 
    python scripts_NLI/1_make_templates.py --dataset %{dataset} --part all

# run all from dataset using 
[lex_KB/%{dataset}/NLI]
recipe = 
    python scripts_NLI/3_predict_using_tree.py --dataset %{dataset} --part all

# add dependency
[lex_KB/%{dataset}/NLI/%{part}]
recipe = 
    python scripts_NLI/3_predict_using_tree.py --dataset %{dataset} --part all --model NLI

# LANGPRO
[langpro_RUN]
recipe = 
    echo "parList([parts(['train']), parallel(_), prprb, aall, wn_ant, wn_sim, wn_der, constchck, allInt])."
    swipl -f %{langpro_path}/prolog/main.pl %{langpro_path}/WNProlog/wn.pl datasets/SNLI_5_anno/snli_1.0_train_5_anno_sen.pl datasets/SNLI_5_anno/snli_1.0_train_5_anno_ccg.pl

[SNLI_max_%{prob}_%{prob2}_%{step}]
main = %{langpro_path}/prolog/main.pl
sen = datasets/SNLI_5_anno/snli_1.0_train_5_anno_sen.pl
parser_pl = datasets/SNLI_5_anno/snli_1.0_train_5_anno_ccg.pl
wn =  %{langpro_path}/WNProlog/wn.pl
log = results/SNLI_5_anno/debug/snli_1.0_train_5_anno_DEBUG.log
ans = results/SNLI_5_anno/debug/snli_1.0_train_5_anno_DEBUG.ans
low_prob = %{int(prob)} 
high_prob = %{int(prob2)} 
range = %{int(step)}
recipe =
    echo %{prob} %{prob2} , step range %{step}

    mkdir -p results/SNLI_5_anno/debug/

    i_low=%{low_prob}
    i=$(($i_low + %{range}))
    while ((i<=%{high_prob})); do
        echo $i_low $i 
        START_TIME=$SECONDS

        ( time swipl -g "parList([parallel(_), prprb, aall, wn_ant, wn_sim, wn_der, constchk, ral(2), allInt, waif('%{ans}_$i_low-$i')]), entail_some($i_low-$i)" -t halt -f %{main}  %{parser_pl} %{sen} %{wn} ) > %{log}_$i_low-$i 2>&1
        STOP_TIME=$(( SECONDS - START_TIME ))
        echo $STOP_TIME
        echo "-----------"
        i_low=$i
        i=$(($i + %{range}))
    done
    echo $i_low %{high_prob}
    START_TIME=$SECONDS
    ( time swipl -g "parList([parallel(_), prprb, aall, wn_ant, wn_sim, wn_der, constchk, ral(2), allInt, waif('%{ans}_$i_low-%{high_prob}')]), entail_some($i_low-%{high_prob})" -t halt -f %{main}  %{parser_pl} %{sen} %{wn} ) > %{log}_$i_low-%{high_prob} 2>&1
    STOP_TIME=$(( SECONDS - START_TIME ))
    echo $STOP_TIME
    echo "-----------"

# SNLI SINGLE TEST -> debug find broken mem
[SNLI_S_%{prob}_%{prob2}]
main = %{langpro_path}/prolog/main.pl
sen = datasets/SNLI_5_anno/snli_1.0_train_5_anno_sen.pl
parser_pl = datasets/SNLI_5_anno/snli_1.0_train_5_anno_ccg.pl
wn =  %{langpro_path}/WNProlog/wn.pl
log = results/SNLI_5_anno/LRC/base/snli_1.0_train_5_anno_DEBUG.log
ans = results/SNLI_5_anno/LRC/base/snli_1.0_train_5_anno_DEBUG.ans
low_prob = %{int(prob)} 
high_prob = %{int(prob2)} 
recipe =
    echo %{prob} %{prob2} 
    mkdir -p results/SNLI_5_anno/LRC/base/
    swipl -g "parList([parallel(1), prprb, aall, wn_ant, wn_sim, wn_der, constchk, ral(400), allInt, waif('%{ans}')]), entail_some(%{low_prob}-%{high_prob})" -t halt -f %{main}  %{parser_pl} %{sen} %{wn} > %{log} 2>&1

[SNLI_%{prob}_%{prob2}]
main = %{langpro_path}/prolog/main.pl
sen = datasets/SNLI_5_anno/snli_1.0_train_5_anno_sen.pl
parser_pl = datasets/SNLI_5_anno/snli_1.0_train_5_anno_ccg.pl
wn =  %{langpro_path}/WNProlog/wn.pl
log = results/SNLI_5_anno/base/snli_1.0_train_5_anno_DEBUG.log
ans = results/SNLI_5_anno/base/snli_1.0_train_5_anno_DEBUG.ans
low_prob = %{int(prob)} 
high_prob = %{int(prob2)} 
recipe =
    echo %{prob} %{prob2} 
    mkdir -p results/SNLI_5_anno/base/
    swipl -g "parList([parallel(_), prprb, aall, wn_ant, wn_sim, wn_der, constchk, ral(400), allInt, waif('%{ans}')]), entail_some(%{low_prob}-%{high_prob})" -t halt -f %{main}  %{parser_pl} %{sen} %{wn} > %{log} 2>&1

[results/%{dataset}/base/%{part}.ans]
main = %{langpro_path}/prolog/main.pl
sen = datasets/%{dataset}/%{ part_to_sick_filename(part) }_sen_fix.pl
parser_pl = datasets/%{dataset}/%{ part_to_sick_filename(part) }_ccg.pl
wn =  %{langpro_path}/WNProlog/wn.pl
log = results/%{dataset}/base/%{part}.log
recipe =
    mkdir -p results/%{dataset}/base/
    swipl -g "parList([parallel(_), prprb, aall, wn_ant, wn_sim, wn_der, constchk, ral(400), allInt, waif('%{target}')]), entail_all" -t halt -f %{main}  %{parser_pl} %{sen} %{wn} > %{log} 2>&1


# LANGPRO
[results/%{dataset}/abduction/%{part}.ans]
main = %{langpro_path}/prolog/main.pl
sen = datasets/%{dataset}/%{ part_to_sick_filename(part) }_sen_fix.pl
parser_pl = datasets/%{dataset}/%{ part_to_sick_filename(part) }_ccg.pl
wn =  %{langpro_path}/WNProlog/wn.pl
log = results/%{dataset}/abduction/%{part}.log
recipe =
    mkdir -p results/%{dataset}/abduction/
    (time swipl -g "parList([allInt, waif('%{target}'), complete_tree, aall, constchk, wn_ant, wn_sim, wn_der, no_kb, ral(100), parallel(_)]),  train_dev_eval_sick_parts(('%{parser_pl}', '%{sen}'), _SKIP_VAL, _SKIP_TEST, [align-both, constchk, constKB, compTerms, patterns-([_,_@_,(_@_)@_, _@(_@_)])])" -t halt -f %{main}  %{parser_pl} %{sen} %{wn} ) > %{log} 2>&1


# LANGPRO ORG | used for templating
[results/%{dataset}/LRC/%{model}/%{part}.ans]
dep.main = %{langpro_path}/prolog/main.pl
sen = datasets/%{dataset}/%{ part_to_sick_filename(part) }_sen_fix.pl
parser_pl = datasets/%{dataset}/%{ part_to_sick_filename(part) }_ccg.pl
dep.wn =  %{langpro_path}/WNProlog/wn.pl
LRC_file = lex_KB/%{dataset}/%{model}/final/%{part}_lemma_idx.pl
log = results/%{dataset}/LRC/%{model}/%{part}.log
recipe =
    mkdir -p results/%{dataset}/LRC/%{model}/
    swipl -g "parList([parallel(_), aall, wn_ant, wn_sim, wn_der, no_kb, ind_kb, constchk, ral(400), allInt, waif('%{target}')]), entail_all" -t halt -f %{main}  %{parser_pl} %{sen} %{wn} %{LRC_file}> %{log} 2>&1


[results/%{dataset}/LRC/%{model}]
recipe =
    echo %{dataset} %{model}
    produce -b results/%{dataset}/LRC/%{model}/trial.ans
    produce -b results/%{dataset}/LRC/%{model}/train.ans
    produce -b results/%{dataset}/LRC/%{model}/train_trial.ans
    produce -b results/%{dataset}/LRC/%{model}/test_annotated.ans
    
    notify-send -u critical "Script Done"

