######################## Functions #####################
[]
prelude =
    langpro_path = "../LangProAbd/"

    def part_to_sick_filename(part):
        d = {'trial': 'SICK_trial',
             'train': 'SICK_train',
             'test':  'SICK_test_annotated',
             'test_annotated':  'SICK_test_annotated',
             'train_trial': 'SICK_train_trial'
            }
        if "snli" in part or part not in d:
            return part
        else:
            return d[part]

    def sen_filename(part):
        if "snli" in part:
            return f"sen_fix"
        else:
            return f"sen"


########################### DECISION TREE TRAINING AND TESTING ##############################
# Leave One Out Cross Validation
[new_tree_test]
recipe = 
    python /home/thomas/UU/thesis/CCG_parse/scripts_NLI/1_make_templates.py --dataset merged_LRC_words --baseline True --part train
    python /home/thomas/UU/thesis/CCG_parse/scripts_NLI/1_make_templates.py --dataset merged_LRC_words --baseline True --part test
    python /home/thomas/UU/thesis/CCG_parse/scripts_NLI/1_make_templates.py --dataset merged_LRC_words --baseline True --part validation
    python /home/thomas/UU/thesis/CCG_parse/scripts_NLI/1_make_templates.py --dataset ppdb_phrase --baseline True --part ppdb_scrape_disjoint

    python scripts_NLI/2_SICK_NLI_predict.py --dataset ppdb_phrase  --part all --output lex_preds/ppdb_phrase/NLI/pred/ --baseline True
    python scripts_NLI/2_SICK_NLI_predict.py --dataset merged_LRC_words  --part all --output lex_preds/merged_LRC_words/NLI/pred/ --baseline True

    python scripts_NLI/2.5_test_decision_tree.py

# Save new model
[new_tree]
recipe = 
    python /home/thomas/UU/thesis/CCG_parse/scripts_NLI/1_make_templates.py --dataset merged_LRC_words --baseline True --part train
    python /home/thomas/UU/thesis/CCG_parse/scripts_NLI/1_make_templates.py --dataset merged_LRC_words --baseline True --part test
    python /home/thomas/UU/thesis/CCG_parse/scripts_NLI/1_make_templates.py --dataset merged_LRC_words --baseline True --part validation
    python /home/thomas/UU/thesis/CCG_parse/scripts_NLI/1_make_templates.py --dataset ppdb_phrase --baseline True --part ppdb_scrape_disjoint

    python scripts_NLI/2_SICK_NLI_predict.py --dataset ppdb_phrase  --part all --output lex_preds/ppdb_phrase/NLI/pred/ --baseline True
    python scripts_NLI/2_SICK_NLI_predict.py --dataset merged_LRC_words  --part all --output lex_preds/merged_LRC_words/NLI/pred/ --baseline True

    produce -b models/NLI/tasksource

# Script to save the model + add graphs
# Uses wayland??? Quickfix: export QT_QPA_PLATFORM=xcb
[models/NLI/tasksource]
recipe = 
    python scripts_NLI/2.5_train_decision_tree.py
    python scripts_NLI/2.7_visualise_decision_tree.py 

########################### Parse SNLI ##############################
# make CCG and sentence fix files
[datasets_ccg/SNLI_NN]
recipe = 
    mkdir -p datasets_ccg/SNLI_NN
    for f in `ls datasets_original/SNLI_NN/*_NN.jsonl | xargs -n 1 basename`
    do
        python3 scripts_other/nlidata2prolog.py  datasets_original/SNLI_NN/$f  datasets_ccg/SNLI_NN/${f/.jsonl/_sen.pl} --fmt sen.pl  --tokenize native  --corpus snlijson
    done
    echo "--sen done--"

    for f in `ls datasets_original/SNLI_NN/*_NN.jsonl | xargs -n 1 basename`
    do
        python3 scripts_other/nlidata2prolog.py   datasets_original/SNLI_NN/$f  datasets_ccg/SNLI_NN/${f/jsonl/spl} --fmt spl  --tokenize native --corpus snlijson
    done
    echo "--spl done--"

    for f in `ls datasets_ccg/SNLI_NN/*.spl | xargs -n 1 basename`
    do
        # --candc-int-dict_cutoffs="20 20 20 20 150 200 500" --candc-int-betas="0.075 0.03 0.01 0.005 0.001 0.0005 0.00001"
        cat datasets_ccg/SNLI_NN/$f | ../candc/candc/bin/candc --models ../candc/models/models --output datasets_ccg/SNLI_NN/${f/.spl/_ccg.pl}  --candc-printer boxer --candc-parser-noisy_rules=false 2> datasets_ccg/SNLI_NN/${f/.spl/_output.txt} 
        echo "${f/.spl/_cc_ccg.pl} Done"
        grep -o -i failed datasets_ccg/SNLI_NN/${f/.spl/_output.txt}  | wc -l
    done
    echo "---ccg done---"

    python scripts_other/comment_SNLI_problems.py

# ############################ Clues ##########################
# # specify part of dataset
# [lex_preds/%{dataset}/clues/%{part}]
# recipe = 
#     python scripts_clues/csv2pred_raw.py --dataset %{dataset} --part %{part}

# # add dependency
# [lex_KB/%{dataset}/clues/%{part}]
# recipe = 
#     python scripts_clues/to_prolog.py --dataset %{dataset} --part %{part} --model clues

# # run all from dataset using 
# [lex_preds/%{dataset}/clues]
# recipe = 
#     python scripts_clues/csv2pred_raw.py --dataset %{dataset} --part all

# # add dependency
# [lex_KB/%{dataset}/clues]
# recipe = 
#     python scripts_clues/to_prolog.py --dataset %{dataset} --part all --model clues


############################ NLI AUTOMATED ##########################
# RUN USING LEMMA, SLOWER -> ALL MATCHES USED
[snli_%{dataset}-predict]
cond = %{dataset in 'train_5 dev'.split()}
recipe =
    produce -b results/SNLI_NN/LRC/NLI/snli_%{dataset}_NN.ans
    produce -b results/SNLI_NN/LRC_proba/NLI/snli_%{dataset}_NN-0.5.ans
    produce -b results/SNLI_NN/LRC_proba/NLI/snli_%{dataset}_NN-0.9.ans

# RUN USING LEMMA, FAST -> TARGETTED MATCHES USED
[snli_%{dataset}-predict-index]
cond = %{dataset in 'train_5 dev'.split()}
recipe =
    produce -b results/SNLI_NN/LRC/NLI-index/snli_%{dataset}_NN.ans
    produce -b results/SNLI_NN/LRC_proba/NLI-index/snli_%{dataset}_NN-0.5.ans
    produce -b results/SNLI_NN/LRC_proba/NLI-index/snli_%{dataset}_NN-0.9.ans

################# GENERATE NLI KB #################
# Generate part from scratch
[full/%{dataset}/NLI/%{part}]
recipe = 
    # produce -b lex_pairs/%{dataset}
    produce -b lex_preds/%{dataset}/NLI/%{part}
    produce -b lex_KB/%{dataset}/NLI/%{part}

# Generate entire dataset from scratch
[full/%{dataset}/NLI]
recipe =
    # produce -b lex_pairs/%{dataset}
    produce -b lex_preds/%{dataset}/NLI
    produce -b lex_KB/%{dataset}/NLI

################# GENERATE KB PROLOG FILES #################
# Makes the KB from the predictions
[lex_KB/%{dataset}/NLI]
recipe = 
    python scripts_NLI/3_predict_using_tree.py --dataset %{dataset} --part all
    python scripts_NLI/3_predict_using_tree_proba.py --dataset %{dataset} --part all
    python scripts_NLI/3_predict_using_tree_proba.py --dataset %{dataset} --part all --threshhold 0.9

# Makes the part KB from the predictions
[lex_KB/%{dataset}/NLI/%{part}]
recipe = 
    python scripts_NLI/3_predict_using_tree.py --dataset %{dataset} --part %{part}
    python scripts_NLI/3_predict_using_tree_proba.py --dataset %{dataset} --part %{part}
    python scripts_NLI/3_predict_using_tree_proba.py --dataset %{dataset} --part %{part} --threshhold 0.9

################# MAKE DT KB PREDICTIONS  #################
# Makes the templates for full dataset and predicts on them | Baseline -> no templates used but LRC data
[lex_preds/%{dataset}/NLI/baseline]
recipe = 
    python scripts_NLI/1_make_templates.py --dataset %{dataset} --part all
    python scripts_NLI/2_SICK_NLI_predict.py --dataset %{dataset}  --part all --output lex_preds/%{dataset}/NLI/pred/ --baseline True

# Makes the templates for a single part and predicts on them | Baseline -> no templates used but LRC data
[lex_preds/%{dataset}/NLI/%{part}/baseline]
recipe = 
    python scripts_NLI/1_make_templates.py --dataset %{dataset} --part %{part}
    python scripts_NLI/2_SICK_NLI_predict.py --dataset %{dataset}  --part %{part} --output lex_preds/%{dataset}/NLI/pred/ --baseline True

# Makes the templates for a single part and predicts on them
[lex_preds/%{dataset}/NLI/%{part}]
recipe = 
    python scripts_NLI/1_make_templates.py --dataset %{dataset} --part %{part}
    python scripts_NLI/2_SICK_NLI_predict.py --dataset %{dataset} --part %{part} --output lex_preds/%{dataset}/NLI/pred/

# Makes the templates for full dataset and predicts on them
[lex_preds/%{dataset}/NLI]
recipe = 
    python scripts_NLI/1_make_templates.py --dataset %{dataset} --part all
    python scripts_NLI/2_SICK_NLI_predict.py --dataset %{dataset} --part all --output lex_preds/%{dataset}/NLI/pred/

#################
# Get all pairs | no part because fast and should only happen once.
[lex_pairs/%{dataset}]
recipe =
    python scripts_ccg/ccg_main.py --dataset %{dataset}

############################# LangPro Prolog mode ##################################
# LANGPRO
[langpro_run_snli_train]
recipe = 
    echo "parList([prprb, parallel(_), aall, wn_ant, wn_sim, wn_der, constchck, ral(100), allInt])."
    echo "parList([prprb, parallel(_), aall, wn_ant, wn_sim, wn_der, no_kb, no_wn, ind_kb, constchk, ral(100), allInt])."
    swipl -f %{langpro_path}/prolog/main.pl %{langpro_path}/WNProlog/wn.pl datasets_ccg/SNLI_NN/snli_train_5_NN_sen_fix.pl datasets_ccg/SNLI_NN/snli_train_5_NN_ccg.pl lex_KB/SNLI_NN/NLI/final/snli_dev_NN_lemma_idx.pl

[langpro_run_snli_dev]
recipe = 
    echo "parList([prprb, parallel(_), aall, wn_ant, wn_sim, wn_der, constchck, ral(100), allInt])."
    echo "parList([prprb, parallel(_), aall, wn_ant, wn_sim, wn_der, no_kb, no_wn, ind_kb, constchk, ral(100), allInt])."
    swipl -f %{langpro_path}/prolog/main.pl %{langpro_path}/WNProlog/wn.pl datasets_ccg/SNLI_NN/snli_dev_NN_sen_fix.pl datasets_ccg/SNLI_NN/snli_dev_NN_ccg.pl lex_KB/SNLI_NN/NLI/final/snli_dev_NN_lemma_idx.pl

############################# LangPro Debug script ##################################
# runs SNLI part from in range (prob, prob2, step). 
# Useful to find where LangPro gets stuck time wise or breaks wihtout losing big progress
[SNLI_max-%{part}-%{prob}_%{prob2}_%{step}]
main = %{langpro_path}/prolog/main.pl
sen = datasets_ccg/SNLI_NN/%{ part_to_sick_filename(part) }_%{sen_filename(part)}.pl
parser_pl = datasets_ccg/SNLI_NN/%{ part_to_sick_filename(part) }_ccg.pl
wn =  %{langpro_path}/WNProlog/wn.pl
log = results/SNLI_NN/debug/%{ part_to_sick_filename(part) }_DEBUG.log
ans = results/SNLI_NN/debug/%{ part_to_sick_filename(part) }_DEBUG.ans
low_prob = %{int(prob)} 
high_prob = %{int(prob2)} 
range = %{int(step)}
recipe =
    echo %{prob} %{prob2} , step range %{step}

    mkdir -p results/SNLI_NN/debug/

    i_low=%{low_prob}
    i=$(($i_low + %{range}))
    while ((i<=%{high_prob})); do
        echo $i_low $i 
        START_TIME=$SECONDS

        ( time swipl -g "parList([parallel(_), prprb, aall, wn_ant, wn_sim, wn_der, constchk, ral(800), allInt, waif('%{ans}_$i_low-$i')]), entail_some($i_low-$i)" -t halt -f %{main}  %{parser_pl} %{sen} %{wn} ) > %{log}_$i_low-$i 2>&1
        STOP_TIME=$(( SECONDS - START_TIME ))
        echo $STOP_TIME
        echo "-----------"
        i_low=$i
        i=$(($i + %{range}))
    done
    echo $i_low %{high_prob}
    START_TIME=$SECONDS
    ( time swipl -g "parList([parallel(_), prprb, aall, wn_ant, wn_sim, wn_der, constchk, ral(800), allInt, waif('%{ans}_$i_low-%{high_prob}')]), entail_some($i_low-%{high_prob})" -t halt -f %{main}  %{parser_pl} %{sen} %{wn} ) > %{log}_$i_low-%{high_prob} 2>&1
    STOP_TIME=$(( SECONDS - START_TIME ))
    echo $STOP_TIME
    echo "-----------"

############################# LangPro RUN Abduction script ##################################
[results/%{dataset}/abduction/%{train_part}-%{dev_part}-%{cores}.ans]
main = %{langpro_path}/prolog/main.pl
train_sen = datasets_ccg/%{dataset}/%{ part_to_sick_filename(train_part) }_%{sen_filename(train_part)}.pl
dev_sen = datasets_ccg/%{dataset}/%{ part_to_sick_filename(dev_part) }_%{sen_filename(dev_part)}.pl
train_parser_pl = datasets_ccg/%{dataset}/%{ part_to_sick_filename(train_part) }_ccg.pl
dev_parser_pl = datasets_ccg/%{dataset}/%{ part_to_sick_filename(dev_part) }_ccg.pl
wn =  %{langpro_path}/WNProlog/wn.pl
log = results/%{dataset}/abduction/%{train_part}-%{dev_part}.log
recipe =
    mkdir -p results/%{dataset}/abduction/
    echo "%{log}"
    (time swipl -g "parList([allInt, waif('%{target}'), complete_tree, aall, constchk, wn_ant, wn_sim, wn_der, no_kb, ral(100), parallel(%{cores})]),  train_dev_eval_sick_parts(('%{train_parser_pl}', '%{train_sen}'), _SKIP_VAL, ('%{dev_parser_pl}', '%{dev_sen}'), [align-both, constchk, constKB, compTerms, patterns-([_,_@_,(_@_)@_, _@(_@_)])])" -t halt -f %{main} ) > %{log} 2>&1


[results/%{dataset}/abduction/%{train_part}-%{dev_part}.ans]
main = %{langpro_path}/prolog/main.pl
train_sen = datasets_ccg/%{dataset}/%{ part_to_sick_filename(train_part) }_%{sen_filename(train_part)}.pl
dev_sen = datasets_ccg/%{dataset}/%{ part_to_sick_filename(dev_part) }_%{sen_filename(dev_part)}.pl
train_parser_pl = datasets_ccg/%{dataset}/%{ part_to_sick_filename(train_part) }_ccg.pl
dev_parser_pl = datasets_ccg/%{dataset}/%{ part_to_sick_filename(dev_part) }_ccg.pl
wn =  %{langpro_path}/WNProlog/wn.pl
log = results/%{dataset}/abduction/%{train_part}-%{dev_part}.log
recipe =
    mkdir -p results/%{dataset}/abduction/
    (time swipl -g "parList([allInt, waif('%{target}'), complete_tree, aall, constchk, wn_ant, wn_sim, wn_der, no_kb, ral(100), parallel(_)]),  train_dev_eval_sick_parts(('%{train_parser_pl}', '%{train_sen}'), _SKIP_VAL, ('%{dev_parser_pl}', '%{dev_sen}'), [align-both, constchk, constKB, compTerms, patterns-([_,_@_,(_@_)@_, _@(_@_)])])" -t halt -f %{main} ) > %{log} 2>&1

############################# LangPro RUN base script ##################################
[results/%{dataset}/base/%{part}.ans]
main = %{langpro_path}/prolog/main.pl
sen = datasets/%{dataset}/%{ part_to_sick_filename(part) }_sen_fix.pl
parser_pl = datasets/%{dataset}/%{ part_to_sick_filename(part) }_ccg.pl
wn =  %{langpro_path}/WNProlog/wn.pl
log = results/%{dataset}/base/%{part}.log
recipe =
    mkdir -p results/%{dataset}/base/
    swipl -g "parList([parallel(_), prprb, aall, wn_ant, wn_sim, wn_der, constchk, ral(100), allInt, waif('%{target}')]), entail_all" -t halt -f %{main}  %{parser_pl} %{sen} %{wn} > %{log} 2>&1

############################# LangPro RUN LRC script ##################################
[results/%{dataset}/LRC_proba/%{model}-index/%{part}-%{threshhold}.ans]
dep.main = %{langpro_path}/prolog/main.pl
sen = datasets_ccg/%{dataset}/%{ part_to_sick_filename(part) }_%{sen_filename(part)}.pl
parser_pl = datasets_ccg/%{dataset}/%{ part_to_sick_filename(part) }_ccg.pl
dep.wn =  %{langpro_path}/WNProlog/wn.pl
LRC_file = lex_KB/%{dataset}/%{model}/final/%{part}_lemma_idx_proba_%{threshhold}.pl
log = results/%{dataset}/LRC_proba/%{model}-index/%{part}-%{threshhold}.log
recipe =
    mkdir -p results/%{dataset}/LRC_proba/%{model}-index/
    echo %{LRC_file}
    swipl -g "parList([prprb, parallel(_), aall, wn_ant, wn_sim, wn_der, no_kb, no_wn, ind_kb_index, constchk, ral(100), allInt, waif('%{target}')]), entail_all" -t halt -f %{main}  %{parser_pl} %{sen} %{wn} %{LRC_file}> %{log} 2>&1

[results/%{dataset}/LRC_proba/%{model}/%{part}-%{threshhold}.ans]
dep.main = %{langpro_path}/prolog/main.pl
sen = datasets_ccg/%{dataset}/%{ part_to_sick_filename(part) }_%{sen_filename(part)}.pl
parser_pl = datasets_ccg/%{dataset}/%{ part_to_sick_filename(part) }_ccg.pl
dep.wn =  %{langpro_path}/WNProlog/wn.pl
LRC_file = lex_KB/%{dataset}/%{model}/final/%{part}_proba_%{threshhold}.pl
log = results/%{dataset}/LRC_proba/%{model}/%{part}-%{threshhold}.log
recipe =
    mkdir -p results/%{dataset}/LRC_proba/%{model}/
    echo %{LRC_file}
    swipl -g "parList([prprb, parallel(_), aall, wn_ant, wn_sim, wn_der, no_kb, no_wn, ind_kb, constchk, ral(100), allInt, waif('%{target}')]), entail_all" -t halt -f %{main}  %{parser_pl} %{sen} %{wn} %{LRC_file}> %{log} 2>&1

[results/%{dataset}/LRC/%{model}-index/%{part}.ans]
dep.main = %{langpro_path}/prolog/main.pl
sen = datasets_ccg/%{dataset}/%{ part_to_sick_filename(part) }_%{sen_filename(part)}.pl
parser_pl = datasets_ccg/%{dataset}/%{ part_to_sick_filename(part) }_ccg.pl
dep.wn =  %{langpro_path}/WNProlog/wn.pl
LRC_file = lex_KB/%{dataset}/%{model}/final/%{part}_lemma_idx.pl
log = results/%{dataset}/LRC/%{model}-index/%{part}.log
recipe =
    mkdir -p results/%{dataset}/LRC/%{model}-index/
    echo %{LRC_file}
    swipl -g "parList([prprb, parallel(_), aall, wn_ant, wn_sim, wn_der, no_kb, no_wn, ind_kb_index, constchk, ral(100), allInt, waif('%{target}')]), entail_all" -t halt -f %{main}  %{parser_pl} %{sen} %{wn} %{LRC_file}> %{log} 2>&1

[results/%{dataset}/LRC/%{model}/%{part}.ans]
dep.main = %{langpro_path}/prolog/main.pl
sen = datasets_ccg/%{dataset}/%{ part_to_sick_filename(part) }_%{sen_filename(part)}.pl
parser_pl = datasets_ccg/%{dataset}/%{ part_to_sick_filename(part) }_ccg.pl
dep.wn =  %{langpro_path}/WNProlog/wn.pl
LRC_file = lex_KB/%{dataset}/%{model}/final/%{part}_lemma.pl
log = results/%{dataset}/LRC/%{model}/%{part}.log
recipe =
    mkdir -p results/%{dataset}/LRC/%{model}/
    echo %{LRC_file}
    swipl -g "parList([prprb, parallel(_), aall, wn_ant, wn_sim, wn_der, no_kb, no_wn, ind_kb, constchk, ral(100), allInt, waif('%{target}')]), entail_all" -t halt -f %{main}  %{parser_pl} %{sen} %{wn} %{LRC_file}> %{log} 2>&1

############################# LangPro POST script ##################################

# POST
[results/%{dataset}/LRC/%{model}/%{part}-analysis]
# parser.add_argument("log", metavar="log", help="path to log file")
# parser.add_argument("target", metavar="target DIR", help="target directory")
dep.py = scripts_other/seperate_results.py
dep.py2 = scripts_other/sort_file.py
target_dir = results/%{dataset}/LRC/%{model}/%{part}-analysis/
log = results/%{dataset}/LRC/%{model}/%{part}.log
recipe =
    mkdir -p results/%{dataset}/LRC/%{model}/%{part}-analysis
    python3 %{py} %{log} %{target_dir}
    python3 %{py2} %{target_dir}